[tool.poetry]
  name = "pieces"
  version = "0.0.15"
  description = ""  # Add your description here
  authors = ["Pieces <development@pieces.app>"]  # Add your name and email

[tool.poetry.dependencies]
  python = ">=3.9,<3.13"
  beautifulsoup4 = "4.12.3"
  pyperclip = ">=1.8.2"
  websocket-client = "1.7.0"
  pieces_os_client = "1.2.7"
  prompt-toolkit = "^3.0.43"
  rich = "^13.7.1"
  platformdirs = "^4.2.0"

[tool.poetry.group.dev.dependencies]
  pytest = "^8.0.0"
  pyinstaller = "^6.3.0"
#  pieces_os_client = {path = "../pieces-os-client-sdk-for-python/dist/pieces_os_client-1.2.7-py3-none-any.whl"}

[build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
  pieces = "pieces.app:main"


