name: Build installer windows

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Inno Setup
        uses: docker://ghcr.io/goreleaser/inno-setup:latest

      - name: Run Inno Setup
        run: iscc setup.iss

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: |
            setup.exe
