name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install poetry -U
          poetry install 

      - name: Build library
        run: poetry build

      - name: Build stand alone
        run: |
          poetry run pyinstaller -c --onefile src/pieces/app.py  --hidden-import=pydantic_core --add-data=".data/applications.db:." --name=pieces

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/pieces*



