name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      deploy: true
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      pypi_test_token: ${{ secrets.PYPI_TEST_TOKEN }}
      ssh_private_key: ${{ secrets.PIECES_GITHUB_SSH }}
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}
